[project]
name = "ai-for-everyone"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jupyter>=1.1.1",
    "langchain>=0.3.25",
    "openai>=1.86.0",
    "python-dotenv>=1.1.0",
]
